erDiagram

    CalendarEvent {
        SMALLINT calendar_id PK
        SMALLINT event_id PK
    }

    Calendar {
        SMALLINT calendar_id PK
        VARCHAR name
        VARCHAR accesstoken?
        VARCHAR backgroundColor?
        VARCHAR foregroundColor?
    }

    Config {
        INTEGER cfg_id PK
        VARCHAR cfg_name
        LONGVARCHAR cfg_value?
    }

    Deposit {
        SMALLINT dep_ID PK
        DATE dep_Date?
        LONGVARCHAR dep_Comment?
        SMALLINT dep_EnteredBy?
        BOOLEAN dep_Closed
        CHAR dep_Type
    }

    DonatedItem {
        SMALLINT di_ID PK
        VARCHAR di_item
        SMALLINT di_FR_ID
        SMALLINT di_donor_ID
        SMALLINT di_buyer_ID
        SMALLINT di_multibuy
        VARCHAR di_title
        LONGVARCHAR di_description?
        DECIMAL di_sellprice?
        DECIMAL di_estprice?
        DECIMAL di_minimum?
        DECIMAL di_materialvalue?
        SMALLINT di_EnteredBy
        DATE di_EnteredDate
        LONGVARCHAR di_picture?
    }

    DonationFund {
        TINYINT fun_ID PK
        CHAR fun_Active
        VARCHAR fun_Name?
        VARCHAR fun_Description?
        INTEGER fun_Order
    }

    EventAttend {
        INTEGER attend_id PK
        INTEGER event_id
        INTEGER person_id
        TIMESTAMP checkin_date?
        INTEGER checkin_id?
        TIMESTAMP checkout_date?
        INTEGER checkout_id?
    }

    EventAudience {
        SMALLINT event_id PK
        SMALLINT group_id PK
    }

    EventType {
        INTEGER type_id PK
        VARCHAR type_name
        TIME type_defstarttime
        CHAR type_defrecurtype
        CHAR type_defrecurDOW
        CHAR type_defrecurDOM
        DATE type_defrecurDOY
        INTEGER type_active
        INTEGER type_grpid?
    }

    EventCountName {
        INTEGER evctnm_countid PK
        SMALLINT evctnm_eventtypeid
        VARCHAR evctnm_countname
    }

    EventCounts {
        INTEGER evtcnt_eventid PK
        INTEGER evtcnt_countid PK
        VARCHAR evtcnt_countname?
        INTEGER evtcnt_countcount?
        VARCHAR evtcnt_notes?
    }

    Event {
        INTEGER event_id PK
        INTEGER event_type
        VARCHAR event_title
        VARCHAR event_desc?
        LONGVARCHAR event_text?
        TIMESTAMP event_start
        TIMESTAMP event_end
        INTEGER inactive
        INTEGER location_id
        INTEGER primary_contact_person_id
        INTEGER secondary_contact_person_id
        LONGVARCHAR event_url?
    }

    FamilyCustom {
        SMALLINT fam_ID PK
    }

    FamilyCustomMaster {
        VARCHAR fam_custom_Field PK
        SMALLINT fam_custom_Order
        VARCHAR fam_custom_Name
        SMALLINT fam_custom_Special?
        TINYINT fam_custom_FieldSec
        TINYINT type_ID
    }

    Family {
        SMALLINT fam_ID PK
        VARCHAR fam_Name?
        VARCHAR fam_Address1?
        VARCHAR fam_Address2?
        VARCHAR fam_City?
        VARCHAR fam_State?
        VARCHAR fam_Zip?
        VARCHAR fam_Country?
        VARCHAR fam_HomePhone?
        VARCHAR fam_Email?
        DATE fam_WeddingDate?
        TIMESTAMP fam_DateEntered
        TIMESTAMP fam_DateLastEdited?
        SMALLINT fam_EnteredBy
        SMALLINT fam_EditedBy?
        LONGVARCHAR fam_scanCheck?
        LONGVARCHAR fam_scanCredit?
        CHAR fam_SendNewsLetter
        DATE fam_DateDeactivated?
        DOUBLE fam_Latitude?
        DOUBLE fam_Longitude?
        SMALLINT fam_Envelope
    }

    FundRaiser {
        SMALLINT fr_ID PK
        DATE fr_date?
        VARCHAR fr_title
        LONGVARCHAR fr_description?
        SMALLINT fr_EnteredBy
        DATE fr_EnteredDate
    }

    Group {
        SMALLINT grp_ID PK
        TINYINT grp_Type
        SMALLINT grp_RoleListID
        SMALLINT grp_DefaultRole
        VARCHAR grp_Name
        LONGVARCHAR grp_Description?
        BOOLEAN grp_hasSpecialProps?
        BOOLEAN grp_active
        BOOLEAN grp_include_email_export
    }

    GroupPropMaster {
        SMALLINT grp_ID
        TINYINT prop_ID
        VARCHAR prop_Field
        VARCHAR prop_Name?
        VARCHAR prop_Description?
        SMALLINT type_ID
        SMALLINT prop_Special?
        CHAR prop_PersonDisplay
    }

    KioskAssignment {
        INTEGER kasm_ID PK
        INTEGER kasm_kdevId?
        INTEGER kasm_AssignmentType?
        INTEGER kasm_EventId?
    }

    KioskDevice {
        INTEGER kdev_ID PK
        VARCHAR kdev_GUIDHash?
        VARCHAR kdev_Name?
        LONGVARCHAR kdev_deviceType?
        LONGVARCHAR kdev_lastHeartbeat?
        BOOLEAN kdev_Accepted?
        LONGVARCHAR kdev_PendingCommands?
    }

    ListOption {
        SMALLINT lst_ID PK
        SMALLINT lst_OptionID PK
        TINYINT lst_OptionSequence
        VARCHAR lst_OptionName
    }

    Location {
        SMALLINT location_id PK
        SMALLINT location_typeID
        VARCHAR location_name
        VARCHAR location_address
        VARCHAR location_city
        VARCHAR location_state
        VARCHAR location_zip
        VARCHAR location_country
        VARCHAR location_phone
        VARCHAR location_email
        VARCHAR location_timzezone
    }

    MenuLink {
        SMALLINT linkId PK
        VARCHAR linkName?
        VARCHAR linkUri?
        SMALLINT linkOrder?
    }

    Note {
        SMALLINT nte_ID PK
        SMALLINT nte_per_ID
        SMALLINT nte_fam_ID
        SMALLINT nte_Private
        LONGVARCHAR nte_Text?
        TIMESTAMP nte_DateEntered
        TIMESTAMP nte_DateLastEdited?
        SMALLINT nte_EnteredBy
        SMALLINT nte_EditedBy
        VARCHAR nte_Type?
    }

    PersonGroupRole {
        SMALLINT p2g2r_per_ID PK
        SMALLINT p2g2r_grp_ID PK
        SMALLINT p2g2r_rle_ID
    }

    PersonVolunteerOpportunity {
        SMALLINT p2vo_ID PK
        SMALLINT p2vo_per_ID?
        SMALLINT p2vo_vol_ID?
    }

    PersonCustom {
        SMALLINT per_ID PK
    }

    PersonCustomMaster {
        VARCHAR custom_Field PK
        SMALLINT custom_Order
        VARCHAR custom_Name
        SMALLINT custom_Special?
        TINYINT custom_FieldSec
        TINYINT type_ID
    }

    Person {
        SMALLINT per_ID PK
        VARCHAR per_Title?
        VARCHAR per_FirstName?
        VARCHAR per_MiddleName?
        VARCHAR per_LastName?
        VARCHAR per_Suffix?
        VARCHAR per_Address1?
        VARCHAR per_Address2?
        VARCHAR per_City?
        VARCHAR per_State?
        VARCHAR per_Zip?
        VARCHAR per_Country?
        VARCHAR per_HomePhone?
        VARCHAR per_WorkPhone?
        VARCHAR per_CellPhone?
        VARCHAR per_Email?
        VARCHAR per_WorkEmail?
        TINYINT per_BirthMonth
        TINYINT per_BirthDay
        SMALLINT per_BirthYear?
        DATE per_MembershipDate?
        TINYINT per_Gender
        TINYINT per_fmr_ID
        TINYINT per_cls_ID
        SMALLINT per_fam_ID
        SMALLINT per_Envelope?
        TIMESTAMP per_DateLastEdited?
        TIMESTAMP per_DateEntered
        SMALLINT per_EnteredBy
        SMALLINT per_EditedBy?
        DATE per_FriendDate?
        SMALLINT per_Flags
        VARCHAR per_Facebook?
        VARCHAR per_Twitter?
        VARCHAR per_LinkedIn?
    }

    Pledge {
        SMALLINT plg_plgID PK
        SMALLINT plg_FamID?
        SMALLINT plg_FYID?
        DATE plg_date?
        DECIMAL plg_amount?
        CHAR plg_schedule?
        CHAR plg_method?
        LONGVARCHAR plg_comment?
        DATE plg_DateLastEdited
        SMALLINT plg_EditedBy
        CHAR plg_PledgeOrPayment
        TINYINT plg_fundID?
        SMALLINT plg_depID?
        BIGINT plg_CheckNo?
        BOOLEAN plg_Problem?
        LONGVARCHAR plg_scanString?
        SMALLINT plg_aut_ID
        BOOLEAN plg_aut_Cleared
        SMALLINT plg_aut_ResultID
        DECIMAL plg_NonDeductible
        VARCHAR plg_GroupKey
    }

    Property {
        SMALLINT pro_ID PK
        VARCHAR pro_Class
        SMALLINT pro_prt_ID
        VARCHAR pro_Name
        LONGVARCHAR pro_Description
        VARCHAR pro_Prompt?
    }

    PropertyType {
        SMALLINT prt_ID PK
        VARCHAR prt_Class
        VARCHAR prt_Name
        LONGVARCHAR prt_Description
    }

    PredefinedReports {
        SMALLINT qry_ID PK
        LONGVARCHAR qry_SQL
        VARCHAR qry_Name
        LONGVARCHAR qry_Description
        BOOLEAN qry_Count
    }

    QueryParameterOptions {
        SMALLINT qpo_ID PK
        SMALLINT qpo_qrp_ID
        VARCHAR qpo_Display
        VARCHAR qpo_Value
    }

    QueryParameters {
        SMALLINT qrp_ID PK
        SMALLINT qrp_qry_ID
        TINYINT qrp_Type
        LONGVARCHAR qrp_OptionSQL?
        VARCHAR qrp_Name?
        LONGVARCHAR qrp_Description?
        VARCHAR qrp_Alias?
        VARCHAR qrp_Default?
        TINYINT qrp_Required
        TINYINT qrp_InputBoxSize
        VARCHAR qrp_Validation
        INTEGER qrp_NumericMax?
        INTEGER qrp_NumericMin?
        INTEGER qrp_AlphaMinLength?
        INTEGER qrp_AlphaMaxLength?
    }

    RecordProperty {
        SMALLINT r2p_pro_ID PK
        SMALLINT r2p_record_ID PK
        LONGVARCHAR r2p_Value
    }

    Token {
        VARCHAR token PK
        VARCHAR type
        DATE valid_until_date?
        INTEGER reference_id?
        INTEGER remainingUses?
    }

    UserSetting {
        SMALLINT user_id PK
        VARCHAR setting_name PK
        VARCHAR setting_value?
    }

    User {
        SMALLINT usr_per_ID PK
        VARCHAR usr_Password
        BOOLEAN usr_NeedPasswordChange
        TIMESTAMP usr_LastLogin
        SMALLINT usr_LoginCount
        TINYINT usr_FailedLogins
        BOOLEAN usr_AddRecords
        BOOLEAN usr_EditRecords
        BOOLEAN usr_DeleteRecords
        BOOLEAN usr_MenuOptions
        BOOLEAN usr_ManageGroups
        BOOLEAN usr_Finance
        BOOLEAN usr_Notes
        BOOLEAN usr_Admin
        SMALLINT usr_defaultFY
        SMALLINT usr_currentDeposit
        VARCHAR usr_UserName
        VARCHAR usr_Style?
        VARCHAR usr_ApiKey?
        VARCHAR usr_TwoFactorAuthSecret?
        SMALLINT usr_TwoFactorAuthLastKeyTimestamp?
        LONGVARCHAR usr_TwoFactorAuthRecoveryCodes?
        BOOLEAN usr_EditSelf
        DATE usr_CalStart?
        DATE usr_CalEnd?
        DATE usr_CalNoSchool1?
        DATE usr_CalNoSchool2?
        DATE usr_CalNoSchool3?
        DATE usr_CalNoSchool4?
        DATE usr_CalNoSchool5?
        DATE usr_CalNoSchool6?
        DATE usr_CalNoSchool7?
        DATE usr_CalNoSchool8?
        TINYINT usr_SearchFamily?
    }

    UserConfig {
        SMALLINT ucfg_per_id PK
        INTEGER ucfg_id PK
        VARCHAR ucfg_name
        LONGVARCHAR ucfg_value?
        CHAR ucfg_type
        LONGVARCHAR ucfg_tooltip
        CHAR ucfg_permission
        VARCHAR ucfg_cat
    }

    Version {
        SMALLINT ver_ID PK
        VARCHAR ver_version
        TIMESTAMP ver_update_start?
        TIMESTAMP ver_update_end?
    }

    VolunteerOpportunity {
        INTEGER vol_ID PK
        INTEGER vol_Order
        CHAR vol_Active
        VARCHAR vol_Name?
        VARCHAR vol_Description?
    }

    WhyCame {
        SMALLINT why_ID PK
        SMALLINT why_per_ID
        LONGVARCHAR why_join
        LONGVARCHAR why_come
        LONGVARCHAR why_suggest
        LONGVARCHAR why_hearOfUs
    }
